language: java

sudo: false

script:
  - jdk_switcher use oraclejdk7
  - mvn clean verify -P jdk7
  - jdk_switcher use oraclejdk8
  - mvn clean verify -P jdk8

after_success:
  - mvn clean test jacoco:report coveralls:report

notifications:
  email:
    on_failure: change
